#Volumes
volumes:
  node_modules:
    
services:
  #Database
  fullstackshop.db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: P4ssw0rd
    ports:
      - "5432:5432"
  
  #Nuxt Frontend
  fullstackshop.nuxt:
    image: fss.nuxt
    build:
      context: src/Frontend/FullStackShop.Web
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
      - "24678:24678" #For Vite hot module reloading
    volumes:
      - ./src/Frontend/FullStackShop.Web:/src
      - node_modules:/src/node_modules
    labels:
      com.jetbrains.rider.debug: "false"
      com.jetbrains.rider.fast.mode: "false"
  
  # Application API
  fullstackshop.api:
    image: fss.api
    build:
      context: ./src/Backend
      dockerfile: FullStackShop.API/Dockerfile
    environment:
      "ASPNETCORE_Environment": Development
      "ASPNETCORE_Urls": "http://+:8000;https://+:8001"
      "ASPNETCORE_ConnectionStrings__DefaultConnection": "host=fullstackshop.db;port=5432;user id=postgres;database=fss;password=P4ssw0rd"
      "ASPNETCORE_Kestrel__Certificates__Default__Password": "P@ssw0rd"
      "ASPNETCORE_Kestrel__Certificates__Default__Path": "./fssapi.pfx"
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on: 
      - fullstackshop.db
  
  
  #Database Admin
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
        
  

  
  
