CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

CREATE TABLE products_categories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT pk_products_categories PRIMARY KEY (id)
);

CREATE TABLE users (
    _id character varying(256) NOT NULL,
    created_on datetime NOT NULL,
    _email character varying(64) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (_id)
);

CREATE TABLE products (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    _category_id integer NOT NULL,
    _description character varying(2048),
    _name character varying(64) NOT NULL,
    _price numeric(5,2),
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT fk_products_products_categories__category_id1 FOREIGN KEY (_category_id) REFERENCES products_categories (id) ON DELETE CASCADE
);

CREATE INDEX ix_products__category_id ON products (_category_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20231129211743_Initial', '8.0.0');

COMMIT;

