// <auto-generated />
using System;
using FullStackShop.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FullStackShop.EF.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FullStackShop.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("_categoryId")
                        .HasColumnType("integer")
                        .HasColumnName("_category_id");

                    b.Property<string>("_description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("_description");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("_name");

                    b.Property<decimal?>("_price")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("_price");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("_categoryId")
                        .HasDatabaseName("ix_products__category_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("FullStackShop.Domain.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id")
                        .HasName("pk_products_categories");

                    b.ToTable("products_categories", (string)null);
                });

            modelBuilder.Entity("FullStackShop.Domain.Models.User", b =>
                {
                    b.Property<string>("_id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_on");

                    b.Property<string>("_email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("_email");

                    b.HasKey("_id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FullStackShop.Domain.Models.Product", b =>
                {
                    b.HasOne("FullStackShop.Domain.Models.ProductCategory", "_category")
                        .WithMany()
                        .HasForeignKey("_categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_products_categories__category_id1");

                    b.Navigation("_category");
                });
#pragma warning restore 612, 618
        }
    }
}
